using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

/*
{
   "results" : [
      {
         "address_components" : [
            {
               "long_name" : "5-48",
               "short_name" : "5-48",
               "types" : [ "street_number" ]
            },
            {
               "long_name" : "49th Avenue",
               "short_name" : "49th Ave",
               "types" : [ "route" ]
            },
            {
               "long_name" : "Long Island City",
               "short_name" : "LIC",
               "types" : [ "neighborhood", "political" ]
            },
            {
               "long_name" : "Queens",
               "short_name" : "Queens",
               "types" : [ "political", "sublocality", "sublocality_level_1" ]
            },
            {
               "long_name" : "Queens County",
               "short_name" : "Queens County",
               "types" : [ "administrative_area_level_2", "political" ]
            },
            {
               "long_name" : "New York",
               "short_name" : "NY",
               "types" : [ "administrative_area_level_1", "political" ]
            },
            {
               "long_name" : "United States",
               "short_name" : "US",
               "types" : [ "country", "political" ]
            },
            {
               "long_name" : "11101",
               "short_name" : "11101",
               "types" : [ "postal_code" ]
            }
         ],
         "formatted_address" : "5-48 49th Ave, Long Island City, NY 11101, USA",
         "geometry" : {
            "location" : {
               "lat" : 40.7434123,
               "lng" : -73.9542376
            },
            "location_type" : "APPROXIMATE",
            "viewport" : {
               "northeast" : {
                  "lat" : 40.7447612802915,
                  "lng" : -73.9528886197085
               },
               "southwest" : {
                  "lat" : 40.7420633197085,
                  "lng" : -73.95558658029151
               }
            }
         },
         "place_id" : "ChIJv4bbdSNZwokRCgKfDGF8az8",
         "types" : [ "establishment", "food", "point_of_interest", "restaurant" ]
      }
   ],
   "status" : "OK"
}

*/


//
//
//
// This code was generated by the web page http://json2csharp.com/
//
// This approach was suggested by https://stackoverflow.com/questions/34043384/easiest-way-to-parse-json-response
// Here, is what it says:
// Follow these steps:
//
//    1. Convert your JSON to C# using json2csharp.com;
//    2. Create a class file and put the above generated code in there;
//    3. Add the Newtonsoft.Json library to your project using the Nuget Package Manager;
//    4. Convert the JSON received from your service using this code:
//
//     RootObject r = JsonConvert.DeserializeObject<RootObject>(json);
//
// (Feel free to rename RootObject to something more meaningful to you.The other classes should remain unchanged.)
//
namespace GetAddressData
{

    public class AddressComponent
    {
        public string long_name { get; set; }
        public string short_name { get; set; }
        public List<string> types { get; set; }
    }

    public class Location
    {
        public double lat { get; set; }
        public double lng { get; set; }
    }

    public class Northeast
    {
        public double lat { get; set; }
        public double lng { get; set; }
    }

    public class Southwest
    {
        public double lat { get; set; }
        public double lng { get; set; }
    }

    public class Viewport
    {
        public Northeast northeast { get; set; }
        public Southwest southwest { get; set; }
    }

    public class Geometry
    {
        public Location location { get; set; }
        public string location_type { get; set; }
        public Viewport viewport { get; set; }
    }

    public class Result
    {
        public List<AddressComponent> address_components { get; set; }
        public string formatted_address { get; set; }
        public Geometry geometry { get; set; }
        public string place_id { get; set; }
        public List<string> types { get; set; }
    }

    public class RootObject
    {
        public List<Result> results { get; set; }
        public string status { get; set; }
    }
}
